### ISSUE TITLE
docker-compose is installed but it runs in error  on bento/centos-7 (7.8) vagrant box.

### ISSUE THREAD

**Issue by bayeslearnerold** [robertdebock/ansible-role-docker_ce#6]
Hi, 
It seems that there is some  version mismatch between python docker-compose etc, it seems to be an error with python 2.7 which is no longer supported?
An yum install of docker-compose seems to work ok, because it will download and install python 3.6.  

I tried your roles and it seems docker-compose is installed but won't run:
[vagrant@hdp jenkins-sa]$ docker-compose up 
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 7, in <module>
    from compose.cli.main import main
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 14, in <module>
    import docker.errors
  File "/usr/lib/python2.7/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/lib/python2.7/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 5, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 32, in <module>
    from .exceptions import InvalidURL
  File "/usr/lib/python2.7/site-packages/requests/exceptions.py", line 10, in <module>
    from urllib3.exceptions import HTTPError as BaseHTTPError
  File "/usr/lib/python2.7/site-packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 31, in <module>
    from .connection import (
  File "/usr/lib/python2.7/site-packages/urllib3/connection.py", line 45, in <module>
    from .util.ssl_ import (
  File "/usr/lib/python2.7/site-packages/urllib3/util/__init__.py", line 5, in <module>
    from .request import make_headers
  File "/usr/lib/python2.7/site-packages/urllib3/util/request.py", line 5, in <module>
    from ..exceptions import UnrewindableBodyError
ImportError: cannot import name UnrewindableBodyError

**Comment by robertdebock** [comment]
Okay, I'll try to find a solution, there is sufficient information in the issue, thanks!

**Comment by robertdebock** [comment]
CI confirms this issue. Still working on it.

**Comment by robertdebock** [comment]
It's fixed by moving docker-compose to a new role: robertdebock.docker_compose.

Thanks for letting me know about the issue!
